name: Publish new release

on:
  workflow_run:
    workflows:
      - Build binaries
    types:
      - "completed"

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Dump event context
        env:
          CONTEXT: ${{ toJson(github) }}
        run: |
          echo $CONTEXT

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: |
          echo "Could not trigger a release!"

  release:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Download artifacts from build stage
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          name: release-artifacts
          path: releases/

      - name: Generate sha256 checksum and gpg signatures for release artifacts
        uses: livepeer/action-gh-checksum-and-gpg-sign@latest
        with:
          artifacts-dir: releases
          release-name: ${{ github.ref_name }}
          gpg-key: ${{ secrets.CI_GPG_SIGNING_KEY }}
          gpg-key-passphrase: ${{ secrets.CI_GPG_SIGNING_PASSPHRASE }}

      - name: Release to github
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            releases/*
